 <?php

//include("../../model/config.php");

        // $max_number="select MAX(NUMBER) as 'number' from SALES_ORDER_HEADER where NUMBER NOT LIKE 'Q%'";
        //  $max_number_result = odbc_exec($connection,$max_number);
        //  $max_id = odbc_result($max_number_result, 1);
        //  //$max_value1 = $max_id + 1;
        //  $max_value1 = $max_id + $i;
        //  //$max_value = str_pad($max_value1, 3, 0, STR_PAD_LEFT);
        //  $max_value2 = '000'.$max_value1;
        //  $max_value = $max_value2;

//search product information into INVENTORY table =================================
$inventory="select CODE, INV_DESCRIPTION, PROD, BVBUYUOM from INVENTORY where CODE='$sku_line_items' AND WHSE = '04'";
$inventory_result = odbc_exec($connection,$inventory);
$code = odbc_result($inventory_result, 1);
$inv_description = odbc_result($inventory_result, 2);
$prod = odbc_result($inventory_result, 3);
$bvbuyuom = odbc_result($inventory_result, 4);
//End of search product information into INVENTORY table ==========================

if($n!=0){
$insert_sales_order_details = "INSERT INTO SALES_ORDER_DETAIL(
NUMBER,
RECNO,
WHSE,
CODE,
ORDD_DESCRIPTION,
EXTD_DESC,
PROD_CODE,
COSTING_METHOD,
BVBUYUOM,
BVSTKUOM,
BVSELLUOM,
BVORDQTY,
BVCMTDQTY,
BVBOQTY,
BVINVCMTDQTY,
BVEXQTY1,
BVSERQTY,
BVORDQTY_2,
BVCMTDQTY_2,
BVBOQTY_2,
BVINVCMTDQTY_2,
BVEXQTY1_2,
BVSERQTY_2,
BVRETAILPRICE,
BVUNITPRICE,
BVCURRENTCOSTPRICE,
BVAVERAGECOSTPRICE,
BVBASERETAILPRICE,
BVSTATUS,
BVSPECPRICEFLAG,
BVEXNUMPRICEFLAG1,
BVEXNUMPRICEFLAG2,
BVSLSTAXAPPFLAG1,
BVSLSTAXAPPFLAG2,
BVSLSTAXAPPFLAG3,
BVSLSTAXAPPFLAG4,
INV_TAX_NO,
INV_TAX_PCT,
DISCOUNTABLE,
LINE_DISC,
LINE_DISC_AMT,
LOCN,
ITEM_NOTEPAD,
SERIAL_NO,
REQUIRED_DATE,
SHIPPED_DATE,
EX_AMT1,
EX_AMT2,
EX_NUM_FLAG1,
EX_NUM_FLAG2,
EX_NUM_FLAG3,
EX_NUM_FLAG4,
E_ORD_QTY,
E_SHIP_QTY,
E_OPEN_QTY,
E_EX_QTY,
E_LINE_OPEN_AMT,
E_LINE_DISC_AMT,
E_LINE_TOT_AMT,
E_EX_AMT,
BV_GUID,
ITEM_TYPE,
LAST_INV_NO,
LAST_INV_DATE,
PO_NUMBER,
EX_DETAIL_FILLER,
BVRVVERSION,
BVRVMODDATE,
BVRVMODTIME,
BVRVUSERINIT,
BVRVADDDATE,
BVRVADDTIME,
BVRVADDUSERINIT,
COMMENT
)
VALUES(
    '$max_value',
    '$n',
    '04',
    '$code',
    '$inv_description',
    '0',
    '$prod',
    '0',
    '$bvbuyuom',
    '$bvbuyuom',
    '$bvbuyuom',
    '$quantity_line_items',
    '$quantity_line_items',
    '',
    '',
    '',
    '0',
    '$quantity_line_items',
    '',
    '',
    '',
    '',
    '0',
    '',
    '$price_line_items',
    '',
    '',
    '',
    '0',
    '0',
    '0',
    '0',
    '3',
    '3',
    '0',
    '0',
    '0',
    '',
    '1',
    '0.00',
    '0.00',
    '',
    '',
    '0',
    '',
    '',
    '0.00',
    '0.00',
    '0',
    '0',
    '0',
    '0',
    '0.00000',
    '0.00000',
    '0.00000',
    '0.00000',
    '0.00',
    '0.00',
    '0.00',
    '0.00',
    '',
    '1',
    '',
    '',
    '',
    '',
    '7.91',
    '$date_created',
    '',
    '',
    '$date_created',
    '',
    'BV*',
    ''
)";
$insert_sales_order_details_result = odbc_exec($connection,$insert_sales_order_details);
}

?>   